INSERT INTO stations(massif,nomS) VALUES ('Alpes','﻿L\'Alpe du Grand Serre');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','L\'Alpes d\'Huez ');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Arêches-Beaufort');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Les Arcs');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','L\'Audibergue');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','La Moulière');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Autron');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Autrans');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Avoriaz');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Bramans');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Les Brasses');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Chamonix');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Chamrousse');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','La Chèvrerie');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','La Clusaz');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Le Collet d\'Allevard');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Col du Feu');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Combloux');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Les Contamines');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Cordon');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Crévoux');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','La Colmiane');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Les Carroz');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Les Deux Alpes');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Espace Diamants');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Flumet');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Praz-sur-Arly');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Les Saisies');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Crest-Voland');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Notre-Dame-de-Bellecombe');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Flaine');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Font d\'Urle Chaud Clapier');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Les Gets');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Les Grands-Montet');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Le Grand-Bornand');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Greolieres-les-neiges');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Gresse-en-Vercor');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Habère-Poche');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Espace Killy');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Val-d\'Isère');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Tignes');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Hirmentaz');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Bellevaux');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Isola 2000');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Lans-en-Vercors');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Les Karellis');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Les Orres');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Manigod');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Méaudre');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Megève');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Montgenèvre');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Morillon');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Morzine');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','La Norma');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Orcières-Merlette');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','La Plagne');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Les Portes du Soleil');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Praz de Lys');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Sommand');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Pra Loup');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Pralognan-la-Vanoise');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Réallon');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Rencurel');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Risoul 1850');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','La Rosière');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Roubion');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','La Ruchère en Chartreuse');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','La Sambuy-Seythenex');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Samoëns');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Le Sauze');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Les 7 laux');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Saint Hilaire du Touvet');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Saint Pierre de Chartreuse');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Saint Anne-la-Condamine');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Sainte-Foy-Tarentaise');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','St Jean d\'Aulps');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Serre Chevalier');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','La Semnoz');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Sixt-Fer-à-Cheval');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Sommand');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Super-Châtel');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Super Dévoluy');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Super-Saxel');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Les Sybelles');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','La Toussuire');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Le Corbier');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Saint Jean d\'Avres');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Saint-Sorlin d\'Avres' );
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Saint-Colomban-des-Villards');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Les Bottières');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Les Trois Vallées');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Courchevel');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Méribel');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','La Tania');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Brides-les-Bains');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Saint-Martin-de-Belleville');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','les Menuires');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Val Thorens');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Valberg');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Val Cenis');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Valfréjus');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Valloire');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Valmeinier');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Valmorel');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Vars');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Vaujany');
INSERT INTO stations(massif,nomS) VALUES ('Alpes','Villard-de-Lans');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Arette');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Artouste');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Ax 3 Domaines');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Barèges');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Bourg-d\'Oeuil');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Cauterets');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Font-Romeu');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Formiguères');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Gourette');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Guzet-neige');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Hautacam');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','La Mongie');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','La Pierre Saint-Martin');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Le Mourtis');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Les Angles');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Le Somport');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Luchon-Superbagnères');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Luz-Ardiden');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Nistos cap nestes');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Peyragudes');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Piau-Engaly');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Porté-Puymorens');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Puyvalador');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Puigmal');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Saint-Lary');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Superbagnères');
INSERT INTO stations(massif,nomS) VALUES ('Pyrénées','Val-Louron');
INSERT INTO stations(massif,nomS) VALUES ('Massif central','Le Lioran');
INSERT INTO stations(massif,nomS) VALUES ('Massif central','Super-Besse');
INSERT INTO stations(massif,nomS) VALUES ('Massif central','Mont-Dore');
INSERT INTO stations(massif,nomS) VALUES ('Massif central','Chastreix-Sancy');
INSERT INTO stations(massif,nomS) VALUES ('Massif central','Chalmazel');
INSERT INTO stations(massif,nomS) VALUES ('Massif central','Prat Peyrot');
INSERT INTO stations(massif,nomS) VALUES ('Massif central','Brameloup');
INSERT INTO stations(massif,nomS) VALUES ('Massif central','Laguiole');
INSERT INTO stations(massif,nomS) VALUES ('Massif central','St urcize');
INSERT INTO stations(massif,nomS) VALUES ('Jura','Les Fourgs');
INSERT INTO stations(massif,nomS) VALUES ('Jura','Métabief Mont d\'Or');
INSERT INTO stations(massif,nomS) VALUES ('Jura','Rochejean');
INSERT INTO stations(massif,nomS) VALUES ('Jura','Mijoux Lélex');
INSERT INTO stations(massif,nomS) VALUES ('Jura','Crozet');
INSERT INTO stations(massif,nomS) VALUES ('Jura','La Vattay');
INSERT INTO stations(massif,nomS) VALUES ('Jura','La Faucille');
INSERT INTO stations(massif,nomS) VALUES ('Jura','Menthères');
INSERT INTO stations(massif,nomS) VALUES ('Jura','Les Rousses');
INSERT INTO stations(massif,nomS) VALUES ('Jura','La Dôle (Suisse)');
INSERT INTO stations(massif,nomS) VALUES ('Jura','Bois-d\'Amont');
INSERT INTO stations(massif,nomS) VALUES ('Jura','Lamoura');
INSERT INTO stations(massif,nomS) VALUES ('Jura','Prémanon');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Ballon d\'Alsace');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Champ du Feu');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Col de la Schlucht');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Cornimont');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','La Bresse');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Lac Blanc/Le Bonhomme');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Le Frenz');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Saint-Amarin');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Le Gaschney');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Le Haut du Tôt');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Le Schnepfenried');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Le Tanet');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Le Valtin');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Les Trois-Fours');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Gérardmer-Ski');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Girmont');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Val d\'Ajol ');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Markstein');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Saint-Maurice-sur-Moselle');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Ventron Frère Joseph');
INSERT INTO stations(massif,nomS) VALUES ('Vosges','Xonrupt-Longemer');
INSERT INTO stations(massif,nomS) VALUES ('Corse','Ghisoni-Capanelle');
INSERT INTO stations(massif,nomS) VALUES ('Corse','Val d\'Ese');
INSERT INTO stations(massif,nomS) VALUES ('Corse','Vergio');
INSERT INTO stations(massif,nomS) VALUES ('Corse','Haut-Asco');